### ISSUE TITLE
Title isn't centered on iPhone 6/6+

### ISSUE THREAD

**Issue by andrei512** [vtourraine/AcknowList#1]
![screen_shot_2015-11-26_at_12 48 04_am](https://cloud.githubusercontent.com/assets/1370375/11423629/be0c9012-944e-11e5-95e5-e66d7d3e0751.png)

**Comment by vtourraine** [comment]
Thanks for the feedback. The title for this controller is just the system `title` property, so we’re not managing alignement in itself. 

I can see two reasons:

- Extra space characters at the beginning of the title string being parsed from the plist. I’ve never seen this behavior, but it might depend on your CocoaPods version, or maybe Swift version.
- The back button item title is present but not visible, moving the title to the right. This button title should be localized “Acknowledgements” (the title of the upper controller), or localized “Back” when there’s not enough space.

The second explanation seems more likely, but really, I can’t tell without your code. Could you please try to debug your situation to understand more precisely what is going on? Or maybe share your project code to help us reproduce this issue? Thanks in advance.

**Comment by vtourraine** [comment]
Closing it for now. Feel free to ask me to reopen this issue if the problem persists.
