### ISSUE TITLE
Dependency licenses are not displaying

### ISSUE THREAD

**Issue by HenryGlendening** [vtourraine/AcknowList#105]
I'm using SwiftUI and presenting the `AcknowListSwiftUIView`, init'd with `AcknowParser.defaultPackages()` to load my `Package.resolved` file.

When I run my app, my NavigationLink successfully presents the AcknowListSwiftUIView, showing a scrolling list of all of the app's dependencies. When I select one, the app navigates to a new screen that shows the dependency's name at the top, but the rest of the view is empty instead of showing the library license.

I'm having the same experience on both iOS 16.0 and tvOS 16.0 (physical device and simulator)

**Comment by vtourraine** [comment]
Hello @HenryGlendening,

Thanks a lot for your feedback! When we added SPM support in AcknowList 3.0, I’m afraid I forgot to update the SwiftUI view to handle acknowledgements with a URL but no text.

The good news is that it shouldn’t be too hard to fix that. I’ve already created a branch with a pull request that you can test. Please let me know if that works for you: https://github.com/vtourraine/AcknowList/pull/106
