### ISSUE TITLE
Exclude a pod

### ISSUE THREAD

**Issue by iadcialim** [vtourraine/AcknowList#107]
Hi. How do exclude a pod and not show up in the Pods-acknowledgements.plist?

**Comment by vtourraine** [comment]
Hello 👋 

You can let the view controller automatically imports all the pods from the plist file, then remove an item from the `acknowledgements` property before presenting the controller.

Like this:

``` swift
let viewController = AcknowListViewController()
if let index = viewController.acknowledgements.firstIndex(where: { $0.title == "PodABC" }) {
    viewController.acknowledgements.remove(at: index)
}
navigationController?.pushViewController(viewController, animated: true)
```

**Comment by iadcialim** [comment]
thanks @vtourraine. it worked!
