### ISSUE TITLE
Problem with transparent list and rows 

### ISSUE THREAD

**Issue by jaceklapinski** [vtourraine/AcknowList#111]
Hello, 

I have a strange problem with the transparent background in your lib :) 

Below screenshots 

![Simulator Screenshot - iPhone 15 Pro - 2023-11-13 at 09 50 19](https://github.com/vtourraine/AcknowList/assets/16321564/1dc713d2-dd0f-4ce3-90f7-388e3a74e383)
![Simulator Screenshot - iPhone 15 Pro - 2023-11-13 at 09 50 23](https://github.com/vtourraine/AcknowList/assets/16321564/8da8f597-9ae5-41ae-8965-1ba3ad2e0d50)

XCode Version 15.0.1 (15A507)

How I show AcknowListViewController:

```
       let viewController = AcknowListViewController()
       let nvc = UINavigationController(rootViewController: viewController)
       self?.present(nvc, animated: true)
```

When I start scroll list, rows in table view gets colorized 

Best !

**Comment by vtourraine** [comment]
That’s odd... Are you doing some kind of `UIAppearance` customization somewhere else, maybe?

**Comment by jaceklapinski** [comment]
Yeah ... you are right i found this line in the project: 

`UITableView.appearance().backgroundColor = .clear`

Sorry, I missed that before.

**Comment by vtourraine** [comment]
Glad we solved it 👍
