### ISSUE TITLE
Unable to make it work with SwiftUI on macOS

### ISSUE THREAD

**Issue by bourquep** [vtourraine/AcknowList#114]
I instantiate the view like this:

```
NavigationView {
  AcknowListSwiftUIView(acknowList: AcknowParser.defaultPackages()!)
}
```

And I get this result:

![CleanShot 2023-12-23 at 10 37 08@2x](https://github.com/vtourraine/AcknowList/assets/65096/2d5c7e52-02e7-4179-9613-726410f1ede0)

Clicking on the buttons does nothing.

**Comment by vtourraine** [comment]
Thank you for reporting this!

I’ll try to investigate, but feel free to submit a pull request if you manage to fix it.

**Comment by bourquep** [comment]
@vtourraine I am no longer setup to test this, as I've moved to another library, but I'll give it a shot soon and get back to you!

**Comment by vtourraine** [comment]
@bourquep Thanks for the update, I’m looking forward to your feedback. 👍
