### ISSUE TITLE
Cocoapods version & readme not up to date

### ISSUE THREAD

**Issue by iDevelopper** [vtourraine/AcknowList#117]
Hello,

When searching AcknowList on Cocoapods, version is not up to date and on the detail page the readme is not up to date.

**Comment by vtourraine** [comment]
You’re right, I couldn’t push the last version (3.0.1) to CocoaPods earlier this year. I was getting confusing build errors, I don’t remember what specifically. I’ve just tried again with the latest CocoaPods/Xcode, it should have it now.

More importantly, I’ll push the new version today (3.1.0). 🎉

**Comment by iDevelopper** [comment]
Hello,

Version 3.1.0 has been updated, but still when searching AcknowList on Cocoapods, version is not up to date and on the detail page the readme is not up to date.

**Comment by vtourraine** [comment]
Hum, that’s really odd. The version number is correct (https://cocoapods.org/pods/AcknowList), but the README is indeed outdated.

<img width="1272" alt="Screenshot 2024-01-27 at 21 39 40" src="https://github.com/vtourraine/AcknowList/assets/886053/69083a1f-d8e0-499d-b2ef-75e48cf23a4c">

I wonder if this affects other pods as well...

**Comment by vtourraine** [comment]
I’ve looked again at other libraries (like Alamofire) and noticed similarly outdated READMEs. So I’ll consider this a CocoaPods issue, and close this issue.
