### ISSUE TITLE
[Feature]: Add Privacy Manifest 

### ISSUE THREAD

**Issue by LaurentChennaouiDD** [vtourraine/AcknowList#120]
Apple is requiring app developers and third party SDKs to declare their use of the Required Reason APIs via a Privacy Manifest.

Is AcknowList planning to add this to the iOS SDK? And if not, could it be added? Thanks!

[Privacy Manifest - Apple Documents](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files)
[Required Reason API Documents](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api)

Thanks!

**Comment by vtourraine** [comment]
Hello Laurent, and thank you for raising this issue.

To my knowledge, AcknowList doesn’t use any of those privacy-related APIs. I don’t see the point of including an empty privacy manifest, but maybe it would be useful to clarify the situation? Or just with a mention in the repo README?

**Comment by LaurentChennaouiDD** [comment]
Hello Vincent,
Indeed if you're not using any of those privacy APIs, I don't see the point either.
We will submit to Apple our build as it is and will let you know if we get any feedback from them related to your library.

Thank you btw for your prompt response.
