### ISSUE TITLE
Customisation of cells on AcknowListViewController

### ISSUE THREAD

**Issue by gerbiljames** [vtourraine/AcknowList#13]
I've had a think about this one and I'm just not sure about how to do it. I tried subclassing `UITableViewCell` and using `UIAppearance` but for some reason `UITableViewCell`s dont support it for most of their properties.

One way of offering this would be to provide a `UITableViewCell` subclass (`AcknowCell`) which has a customisation function which can be overridden. My issue with this is how should `AcknowListViewController` be told to use a custom cell implementation. I don't think we should add any new parameters to the constructors but it would be possible to add a property to `AcknowListViewController` which specifies which cell class it should use.

What do you think?

**Comment by vtourraine** [comment]
It’s been a frequent interrogation on the original Objective-C [project](https://github.com/vtourraine/VTAcknowledgementsViewController).

Having a “class” parameter isn’t a well-established UIKit pattern (you can find it in AppKit, for `NSControl` and `NSCell`, but that’s not a great example to follow IMO). 

I’d prefer to keep the table view controller as simple as possible, while letting the door open to subclassing, if you need to customize something (the cells, the header/footer, etc). So in this case, I would override `tableView(:, cellForRowAtIndexPath:)`, and re-configure the cell from the main implementation, or even initialize a different cell class.

You mentioned `UIAppearance`, and it might be interesting to investigate that further. I don’t know if we can better support it for this kind of customization. That would seem like a more elegant approach, if possible.

**Comment by vtourraine** [comment]
Looked into `UIAppearance` ([doc](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIAppearance_Protocol/index.html)), and you’re right, it’s too limited for table view cells.

**Comment by gerbiljames** [comment]
You're right about subclassing being the right way to go. I implemented it in my own project and it worked fine apart from being forced to implement some constructors on my subclass which shouldnt have been necessary. This was due to the same irregularity around the `init(coder:)` constructor which I found when writing the localization tests and will be fixed in 0.3.

**Comment by vtourraine** [comment]
Speaking of which, time to release 0.3. It should be available now.
