### ISSUE TITLE
Possibility to provide own localization

### ISSUE THREAD

**Issue by orschaef** [vtourraine/AcknowList#15]
The latest AcknowList update changed my navigationItem title to "Danksagungen" for German localization. This translation is not completely wrong but you would often use another word (like "Lizenzen" what equals "licences")

I would prefer to provide my own localization.

Suggestions:

* Give possibility to ship a custom .strings file
or
* Provide public properties to set the title

**Comment by vtourraine** [comment]
That’s a totally legitimate request, and I think you just need to update the `title` property (inherited from `UIViewController`).

**Comment by orschaef** [comment]
Well, yes ... thats ok for this certain case. It was too obvious ;) But maybe it makes sense to provide certain properties or any functionality to solve this better in the future?

**Comment by vtourraine** [comment]
Glad to hear that it works.

I’d be happy to improve this use-case, but I don’t want to duplicate an existing property. Do you have any suggestion on how to better address this issue? Maybe we should simply mention this possibility in the readme?

**Comment by orschaef** [comment]
Sorry for the late response.

Right at the moment I have no better idea. Let's close the issue for now. If I come around with THE SOLUTION™ I'll contact you again ;-)
