### ISSUE TITLE
AcknowList is not supported by Xcode 8 (Swift 2.3 required)

### ISSUE THREAD

**Issue by honkmaster** [vtourraine/AcknowList#18]
Xcode 8 only supports development in projects with Swift 2.3 or Swift 3.0. As AcknowList is build with Swift 2.2 it can currently not be used in Xcode 8. A syntax update can be done automatically and would be greatly appreciated. How is your opinion?

**Comment by vtourraine** [comment]
We have a [`swift-3`](https://github.com/vtourraine/AcknowList/tree/swift-3) branch, and it should compile with Xcode 8 beta 6.

Do you think I should merge this into master as soon as the Xcode 8 GM gets available, and push a new pod update? That seems reasonable, but on the other hand I'm not sure if everybody is ready to switch to Swift 3 on day 1.

**Comment by honkmaster** [comment]
From what I read Xcode 8 ships with Swift 2.3 and Swift 3. By default Swift 3 is activated and you have to set `Use Legacy Swift Language Version` to even use 2.3. Therefore I would recommend merging it as soon as Xcode goes GM.

**Comment by vtourraine** [comment]
That's interesting. So I should probably ship a version for Swift 2.3 then another one with Swift 3, to let people stick with 2.3 for a while if they want/need. Thanks for the feedback!

**Comment by vtourraine** [comment]
Well, I've just ran the Xcode 8 Swift 2.3 conversion assistant, and the result is: "No source changes necessary". 

Simply need to update the README, I guess. I'll still probably push it as a new version, just to mark a release with Swift 2.3.

**Comment by robbiet480** [comment]
Are there plans to publish the Swift 2.3 or 3 versions on CocoaPods? From looking at the projects I'm using it seems most are publishing Swift 3 to CocoaPods and any Swift 2.3 users specify a specific 2.3 branch.

**Comment by vtourraine** [comment]
Alright, Xcode 8, here we come. 🎉

I've published `1.0.2` for Swift 2.3, then `1.1` for Swift 3. If someone needs to stick to an older version, this will require a specific past AcknowList version from now on.
