### ISSUE TITLE
Example Issue

### ISSUE THREAD

**Issue by AmauryVela** [vtourraine/AcknowList#20]
> dyld: Library not loaded: @rpath/AcknowList.framework/AcknowList
>   Referenced from: /var/containers/Bundle/Application/1D2D6165-1423-4932-BC3E-FE878D989929/AcknowExample.app/AcknowExample
>   Reason: image not found

**Comment by vtourraine** [comment]
Thanks for opening an issue, but could you give us a bit of context?

**Comment by vtourraine** [comment]
Closing this issue, need more info to move forward.
