### ISSUE TITLE
Thoughts on handling special licenses

### ISSUE THREAD

**Issue by kevinvanderlugt** [vtourraine/AcknowList#29]
Howdy,

Thanks for this super useful tool!  I just started using it and it's super helpful.  One issue (not with your project) but when using GooglePlacePicker pod and a few other Google pods they actually have this weird license 

![simulator screen shot jun 29 2017 2 21 44 pm](https://user-images.githubusercontent.com/1927969/27713827-5e1a316a-5ce2-11e7-8141-7b1a80b5c99a.png)

I was wondering if you had any thoughts on how to best handle this?   My thought is to subclass `AcknowListViewController` and override `    func commonInit(acknowledgementsPlistPath: String?) {` then look specifically for these special license requirements.   

Would you be interested in having something that handles these special licenses by letting the `AcknowParser` take a list of overrides for ["pod name": some closure that returns a string]?   Totally fine if you don't want to add that complexity.

Cheers!

**Comment by vtourraine** [comment]
Hello Kevin, and thanks for your feedback!

I agree that this kind of licenses is problematic, but it seems like there’s no good universal solution.

When I need to edit the licenses, I just update the `acknowledgements` property on `AcknowListViewController` before presenting it. No need to subclass. Would that be a reasonable solution, in the context of your project?

**Comment by klwoon** [comment]
Could you post some example here how to update the `acknowledgements` property? I tried to modify the `text` but it won't allowed: `Cannot assign to property: 'text' is a 'let' constant`.

Thanks.

**Comment by vtourraine** [comment]
@klwoon Sure. Here’s an example, I manually set the `acknowledgements` property with hard-coded values:

``` swift
let viewController = AcknowListViewController()
viewController.acknowledgements = [Acknow(title: "Test 1", text: "ABC"), Acknow(title: "Test 2", text: "DEF")]
navigationController?.pushViewController(viewController, animated: true)
```

An individual `Acknow` instance is immutable, this is why you had the error when you tried to edit the `text` property directly. You need to edit the `acknowledgements` array instead. Note that you can also use the Swift `filter` method to keep some values for the original array.

**Comment by klwoon** [comment]
Thanks for the example!

**Comment by klwoon** [comment]
@vtourraine Can you help with this error?

`let ack = Acknow(title: "ABC", text: "ABC", license: "ABC")`

` 'Acknow' initializer is inaccessible due to 'internal' protection level`

**Comment by vtourraine** [comment]
@klwoon Are you using the latest version of the library (v1.2)?

**Comment by klwoon** [comment]
@vtourraine Yes, v1.2

**Comment by vtourraine** [comment]
@klwoon Can you please open a new GitHub Issue, and we’ll discuss it there? Thanks!
