### ISSUE TITLE
'Acknow' initializer is inaccessible due to 'internal' protection level

### ISSUE THREAD

**Issue by klwoon** [vtourraine/AcknowList#30]
`let ack = Acknow(title: "ABC", text: "ABC", license: "ABC")` gives the error:

`'Acknow' initializer is inaccessible due to 'internal' protection level`

Using v1.2

**Comment by klwoon** [comment]
I just check the `Acknow.swift` under Pod folder, it's different with your latest commit.

**Comment by vtourraine** [comment]
That’s... interesting. And if you manually update `Acknow.swift` to the latest version (1.2 or master), does it compile?

**Comment by klwoon** [comment]
If point to `master` branch then no more compilation error:
`pod 'AcknowList', :git => 'git@github.com:vtourraine/AcknowList.git', :branch => 'master'`

Could it be the podspec is referring to an older version? (I'm no cocoapods expert)

**Comment by vtourraine** [comment]
I just checked, and you’re right, the last CocoaPods version isn’t pointing at the latest code changes. This might be related to the new Swift/Xcode version, and how default initializers get exposed now, but anyway, I should definitely update the CocoaPods configuration and push a new version to fix this issue. I’ll take care of this later today.

Thank you so much for the feedback! 👍

**Comment by klwoon** [comment]
Thanks for the great work!

**Comment by vtourraine** [comment]
ℹ️ _Released version 1.2.1 on CocoaPods_
