### ISSUE TITLE
"don’t copy the file itself, just add a reference"

### ISSUE THREAD

**Issue by simonbromberg** [vtourraine/AcknowList#33]
How do you do that? Asking for a friend.
 🤷 😅

**Comment by simonbromberg** [comment]
Oh right, drag from Finder but don't select "copy files if needed" or just "File" > "Add files to …"

**Comment by simonbromberg** [comment]
Hm, the file generated by pod install includes the target name, but the source code is just looking for a file named "Pods-acknowledgements" without the target name.

**Comment by vtourraine** [comment]
Hello Simon, and thanks a lot for your feedback!

We should probably be more explicit about the Xcode “reference” in our documentation; as you noted, the setup can be tricky.

But to address your latest issue: you don’t have to rename the plist file, instead I would suggest that you instantiate the view controller like so:

``` swift
let path = Bundle.main.path(forResource: "Pods-AcknowExample-acknowledgements", ofType: "plist")
let viewController = AcknowListViewController(acknowledgementsPlistPath: path)
```

**Comment by simonbromberg** [comment]
But then why does it use that default never that doesn't match the one the
pod auto generates?

**Comment by vtourraine** [comment]
When I first created this library, that was the default plist file name, so it made sense. I added the option to specify the file path/name later on, but never removed the original initializer. Maybe there are cases where it’s still useful, but maybe not. If not, I should probably remove that init, or at least deprecate it.

**Comment by simonbromberg** [comment]
Yea, or you could change the default name to match the actual default name…

**Comment by vtourraine** [comment]
That’s a great idea. It’s probably more nuanced than that (dealing with spaces, capital letters, etc), but it’s definitely worth exploring. Feel free to send a pull request, otherwise I’ll try to implement that later on.

**Comment by vtourraine** [comment]
@simonbromberg So... I’ve implemented your idea: https://github.com/vtourraine/AcknowList/blob/35289f87d849011749d7bd639a8ba0bcec167418/Source/AcknowListViewController.swift#L152

I was worried that some apps are probably relying on the old file name, so in order _not_ to break the current behavior, I check with FileManager if the file exists, and if not I fallback to the old behavior. I don’t really like having to check explicitly, but that seems like a good compromise overall.

Thanks again for the idea, and feel free to improve it.
