### ISSUE TITLE
Text spacing bug on iPads

### ISSUE THREAD

**Issue by azhang66** [vtourraine/AcknowList#41]
Following commit cf5c82d, there is an issue displaying certain acknowledgements on iPads. With the exception of AcknowList's own license, all of my Pods are affected by this issue (see below pictures for an example with Alamofire). This did not occur in v1.6.0, so I believe it is a regression caused by cf5c82d.

**EDIT**: cf5c82d turned out to not be the problem. The problem was actually due to premature newlines. I've written a PR to fix this here: #43

<img width="662" alt="acknowlist correct" src="https://user-images.githubusercontent.com/10838574/43063800-9403ad5c-8e22-11e8-8f4b-5ed0b96f7c14.png">
<img width="651" alt="alamofire incorrect" src="https://user-images.githubusercontent.com/10838574/43063809-9df59122-8e22-11e8-83b8-8375ef9f58b9.png">

**Comment by azhang66** [comment]
Did some more testing and it's not a regression. Sorry about that! Turned out to be an issue with licenses containing premature line breaks. I wrote a pull request to fix this here: #42

**Comment by vtourraine** [comment]
Fixed with #43
