### ISSUE TITLE
First lines of license appear below navigation bar

### ISSUE THREAD

**Issue by pepejeria** [vtourraine/AcknowList#44]
The first two lines of text will appear below the navigation bar when pushing in the `AcknowViewController` controller. This could be solved by using isTranslucent false on the navigation bar, but a better solution would be to use auto-layout in the `AcknowViewController`.

<img width="419" alt="screen shot 2018-10-05 at 08 59 41" src="https://user-images.githubusercontent.com/1394550/46520664-1eeb3b80-c87d-11e8-9b35-94d5e057108b.png">
<img width="491" alt="screen shot 2018-10-05 at 08 59 55" src="https://user-images.githubusercontent.com/1394550/46520666-1eeb3b80-c87d-11e8-98cb-2dfaf48a259a.png">
<img width="480" alt="screen shot 2018-10-05 at 09 00 16" src="https://user-images.githubusercontent.com/1394550/46520665-1eeb3b80-c87d-11e8-9c59-b8528fbfc97c.png">

**Comment by pepejeria** [comment]
```
if #available(iOS 11.0, *) {
    textView.contentInsetAdjustmentBehavior = .never
}
```

**Comment by pepejeria** [comment]
I solved this by overriding `AcknowViewController`:
```
class LicenseDetailsViewController: AcknowViewController {

    override init(acknowledgement: Acknow) {
        super.init(acknowledgement: acknowledgement)
    }

    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }

    override func viewDidLoad() {
        super.viewDidLoad()
        if #available(iOS 11.0, *) {
            textView?.contentInsetAdjustmentBehavior = .never
        }
        textView?.autoPinEdgesToSuperviewEdges()
    }

}
```
Here auto-layout is used to pin the textView's edges to the superviews and add set the textViews' `contentInsetAdjustmentBehavior` property to never.

**Comment by pepejeria** [comment]
Another solution was to set the `AcknowViewController`'s `edgesForExtendedLayout` to `[]`, but that causes problems with the translucent navigation bar.

**Comment by vtourraine** [comment]
Hello José, and thanks a lot for the feedback.

I’m trying to reproduce the issue you’re describing, but the initial scroll view offset seems fine to me (tested with iOS 9, iOS 11, iOS 12).

Are you sure you’re using the latest version of AcknowList? Can you try with the example project included in this repo?

**Comment by pepejeria** [comment]
I was unable to trigger this by modifying your example project. I have something like this in my app:
```
class ViewController: UIViewController {

    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        navigationController?.setNavigationBarHidden(true, animated: true)
    }

    override func viewWillDisappear(_ animated: Bool) {
        super.viewWillDisappear(animated)
        navigationController?.setNavigationBarHidden(false, animated: true)
    }

    @IBAction func pushAcknowList(_ sender: AnyObject) {
        let viewController = AcknowListViewController(fileNamed: "Pods-acknowledgements")
        navigationController?.pushViewController(viewController, animated: true)
    }
}
```

But couldn't trigger the issue. I guess this can be close then.
