### ISSUE TITLE
No licences

### ISSUE THREAD

**Issue by PiotrStepien** [vtourraine/AcknowList#45]
I installed AcknowList from pods using _pod 'AcknowList'_ and I created a reference between _Pods-bundle name-acknowledgements.plist_ and my **main** target.

In Pods/TargetSupportFiles/Pods/Pods-bundle name-acknowledgements.plist I can see, there is no data (empty file), but in _Pods-Itaka-acknowledgements.markdown_ I can see all licences which I need. How can I fix it?

It is the way, how I create ViewController

`let path = Bundle.main.path(forResource: "Pods-bundle name-acknowledgements", ofType: "plist")
        let licenceVC = AcknowListViewController(acknowledgementsPlistPath: path)`

**Comment by vtourraine** [comment]
Hello Piotr, and thanks for reaching out.

I’m not sure I completely understand the problem, but I can tell you that:

- You need the `plist` file generated by CocoaPods, not the `markdown`.
- You can initialize the main view controller directly with the name of the `plist` file (just make sure that the file is included in the target).

``` swift
let viewController = AcknowListViewController(fileNamed: "Pods-AcknowExample-acknowledgements")
```

I hope that helps. Please let me know if you need further assistance.

**Comment by ApolloZhu** [comment]
This has happened to me. Deleting the Pods folder and rerun pod install solved the problem.

**Comment by PiotrStepien** [comment]
I had to make `pod install` two times and then it works 👍

**Comment by vtourraine** [comment]
Well, this is not ideal, but I’m glad to hear that you’ve managed to fix the situation. 🎉 

I’ll investigate that further if more people report the same issue.

**Comment by brainfuel** [comment]
Same issue
