### ISSUE TITLE
Support for Xcode 11 Swift package manager?

### ISSUE THREAD

**Issue by OkiRules** [vtourraine/AcknowList#53]
Is there any support coming for Xcode 11's new "Swift Package Manager"?

Thanks

**Comment by OkiRules** [comment]
Thanks!

**Comment by lvnkmn** [comment]
You're welcome. However, even though I've been using it successfully for a bit now, the PR has not been merged yet..

**Comment by vtourraine** [comment]
Hello, and sorry for my lack of response to the Swift Package Manager issues and pull requests. I just want to learn a bit more about SPM before merging it in, but I intend to do it soon. Thanks for your patience.

**Comment by tradingstratagem** [comment]
I'm also trying to move all the dependencies to SPM

**Comment by lvnkmn** [comment]
@tradingstratagem if you don’t like waiting, you van use my fork (the one from the PR mentioned above) it works.

@vtourraine there’s really not much to it, but feel free to do more research 👌

**Comment by tradingstratagem** [comment]
I can wait a couple of days/weeks, but thanks for the suggestion

**Comment by vtourraine** [comment]
Good news: I’ve merged the pull request and tagged the changes, so you can now install this library with SPM directly from Xcode.

That being said, we still have a couple of issues with the current implementation (resources, folder structure, unit tests), as summarised here: https://github.com/vtourraine/AcknowList/pull/58#issuecomment-538933567

Please use the dedicated GitHub issues for further discussion. And thank you everybody for contributing!
