### ISSUE TITLE
does not contain bitcode. You must rebuild it with bitcode enabled

### ISSUE THREAD

**Issue by alouanemed** [vtourraine/AcknowList#54]
I added the library with success, but when trying to archive the app for distribution, I am getting this error:

`
:-1: '/Users/alouanemed/Library/Developer/Xcode/DerivedData/app-hcgydxapjqidfmaldslmgpvdjrff/Build/Intermediates.noindex/ArchiveIntermediates/App Beta/BuildProductsPath/Release-iphoneos/AcknowList/AcknowList.framework/AcknowList' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/Users/alouanemed/Library/Developer/Xcode/DerivedData/app-hcgydxapjqidfmaldslmgpvdjrff/Build/Intermediates.noindex/ArchiveIntermediates/App Beta/BuildProductsPath/Release-iphoneos/AcknowList/AcknowList.framework/AcknowList' for architecture arm64`

**Comment by vtourraine** [comment]
I know this issue has been open for a while, but I’m not sure what to do with it. This doesn’t look like an error caused by `AcknowList` itself.

@alouanemed Are you still stuck with this error message?

**Comment by alouanemed** [comment]
I agree with you, I disabled this pluding that stores locally bitcode of all pods and it all went all.
Thank you!

**Comment by vtourraine** [comment]
Alright then. Thank you for the clarification 👍
