### ISSUE TITLE
Swift Package Manager: include localization Bundle

### ISSUE THREAD

**Issue by vtourraine** [vtourraine/AcknowList#59]
How can we include the existing localization Bundle with SPM?

**Comment by ApolloZhu** [comment]
I don't think this is a thing yet, but there's a [proposal](https://github.com/abertelrud/swift-evolution/blob/package-manager-resources/proposals/NNNN-package-manager-resources.md) in development and [discussions in the forum](https://forums.swift.org/t/swift-pm-bundles-and-resources/13981)

**Comment by vtourraine** [comment]
Implemented by #72
