### ISSUE TITLE
Header/Footer Breaks in Xcode 12/iOS 14

### ISSUE THREAD

**Issue by jminutaglio** [vtourraine/AcknowList#68]
In Xcode Version 12.0 (12A7208) & iOS 14, the header and footer views, which should expand to the display size width, now do not format correctly.  This is regardless of setting them in code or in the .plist.

TY in advance for looking at this, we love AcknowList!  :)

<img width="575" alt="Screen Shot 2020-09-16 at 1 27 00 PM" src="https://user-images.githubusercontent.com/49879291/93371601-9d4e0780-f820-11ea-9d70-76c8e5a6eda3.png">

**Comment by vtourraine** [comment]
Thanks a lot for reporting this issue! 

I’ve pushed a quick fix to master, and I’ll release a proper CocoaPods pod update soon.

**Comment by vtourraine** [comment]
Fixed with version 1.9.5 🚀
