### ISSUE TITLE
Header Label Localization

### ISSUE THREAD

**Issue by iDevelopper** [vtourraine/AcknowList#76]
Why the default header label is not localized?

**Comment by vtourraine** [comment]
Are you referring to `This application makes use of the following third party libraries:`?

Originally, I found this line a bit redundant with the title of the screen. On some projects, it’s not entirely accurate (it’s not always “third party libraries”). It’s also a bit uncommon to have an introduction text like that at the top of a table view.

So it wasn’t included when we started localizing this library, and I imagine it would be more difficult to add it now. Of course, you can always add it “manually” when your app configures the view controller.

**Comment by iDevelopper** [comment]
> Are you referring to This application makes use of the following third party libraries:?

Yes

And I think about how to modify the code so that it supports the storyboard. Which is not currently the case.

**Comment by iDevelopper** [comment]
I modified the init but it is not sufficient.
```swift
    public required init?(coder aDecoder: NSCoder) {
        //super.init(style: .grouped)
        super.init(coder: aDecoder)
        /*
        let path = AcknowListViewController.defaultAcknowledgementsPlistPath()
        if let path = path {
            commonInit(acknowledgementsPlistPaths: [path])
        }
        else {
            commonInit(acknowledgementsPlistPaths: [])
        }
        */
    }
```

**Comment by vtourraine** [comment]
> Which is not currently the case.

Ha, that’s a bug then. I’ll look into it, thanks for pointing this out 👍

**Comment by iDevelopper** [comment]
> Which is not currently the case.

The framework does not take into account the texts entered in the IBInspectable fields.

**Comment by vtourraine** [comment]
@iDevelopper Please check out #78

**Comment by iDevelopper** [comment]
I think you need to change the initializer code as well. Try to change the background color of the table view in the storyboard, for example.

    public required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
    }
