### ISSUE TITLE
AcknowList 2.0.0 beta 1

### ISSUE THREAD

**Issue by iDevelopper** [vtourraine/AcknowList#79]
What about Cocoapods?

**Comment by vtourraine** [comment]
It should be available with CocoaPods, you just need to opt-in since it’s marked as beta. Example here: https://github.com/CocoaPods/CocoaPods/issues/7086#issuecomment-332888182

**Comment by iDevelopper** [comment]
Yes I know but I don't understand why you don't want to tag and push to Cocoapods. If you are not sure about all updates and if you need new updates, you will push a new version...

**Comment by vtourraine** [comment]
Well, I’m just slowly surfacing the update, from development version to an actual released build. A couple more weeks, and I’ll release the actual `2.0.0` update.
