### ISSUE TITLE
SwiftUIView is not available on v2.0.3

### ISSUE THREAD

**Issue by inoue0124** [vtourraine/AcknowList#93]
I installed the library via CocoaPods and could not use `AcknowListSwiftUIView`. Compiler said `Cannot find 'AcknowListSwiftUIView' in scope` when I tried to initialize like `let view = AcknowListSwiftUIView()` .

And I found that there are no files of SwiftUI classes in the v2.0.3 release zip.

Could I ask how I can use it for SwiftUI?

**Comment by vtourraine** [comment]
Hello 👋 

The SwiftUI interface is not included in the 2.0.3 release. The plan is to release it with version 2.1, and in the meantime, you can test them on the `main` branch.

Please let us know if you have any feedback on their current implementation.

**Comment by inoue0124** [comment]
OK, I will try them on the main branch!
Thank you.
