### ISSUE TITLE
Plist via SPM

### ISSUE THREAD

**Issue by JulesMoorhouse** [vtourraine/AcknowList#96]
Hi,

I don't believe the SPM will be creating a plist from what I can see, unlike cocoa pods.

Would this need to be created manually ?

This would be an implementation with swiftui.

Thanks in advance,

Jules.

**Comment by vtourraine** [comment]
Hello Jules,

You’re correct, SPM doesn’t generate a plist listing its packages. You could either create this plist yourself (manually or automated), or hardcode instances of `Acknow` and pass them to the list controller.
