### ISSUE TITLE
SwiftUI Views not included in latest Release

### ISSUE THREAD

**Issue by mltbnz** [vtourraine/AcknowList#97]
I figured I had to use the `master` branch to use the SwiftUI View. Since the `README` referenced the SwiftUI Views I was under the conception I just copy the repo url and punch it in Xcode but that didn't work which is totally fine and I am happy with the tool (❤️) but I wanted to raise it here nonetheless

**Comment by vtourraine** [comment]
Good news: I’ve just released version 2.1.0, which includes the SwiftUI classes. 🎉
